# line index -> (prompt, [refs]); refs: Y=young you (protagonist), S=style test, J=Jay, T=Tasha, M=Marco, O=Mr. Okafor, D=Danny
STYLE="Clean bright 2D digital cartoon illustration, simple modern YouTube-explainer style: smooth clean outlines, soft cel shading, natural saturated colors, simple friendly faces with small dot eyes, uncluttered backgrounds. Keep every recurring character exactly like the references. No text, no logos, no brand names. "
YOU="the calm young man with short dark hair in a plain grey hoodie"
OLDER="the calm man (late 20s) with short dark hair, plain grey sweatshirt"
CH={
'J':"Jay: flashy friend, curly black hair, gold chain, red bomber jacket, always holding a shiny new phone",
'T':"Tasha: friend with long box braids and a mustard-yellow jacket",
'M':"Marco: friend with round glasses and a green beanie",
'O':"Mr. Okafor: older Black man in his 60s, short grey beard, reading glasses on a chain, brown cardigan",
'D':"Danny: quiet 19-year-old repair tech, buzz cut, black t-shirt, headphones around his neck",
}
SC={
1:(f"Repair shop counter: Jay slides a phone with a shattered spiderweb screen across the counter toward {OLDER} behind the counter.",['Y','J']),
2:("Close-up of a shiny new expensive phone with a badly shattered spiderweb screen lying on a counter.",['S']),
3:(f"Jay leaning on the repair counter, grinning, asking a favor; {OLDER} behind the counter listening politely.",['Y','J']),
4:(f"Close-up of {OLDER} smiling a small knowing smile behind the counter.",['Y']),
5:(f"Wide shot: {OLDER} stands behind the counter of a busy bright phone repair shop full of technicians and customers; a map on the back wall shows 14 small pins.",['Y']),
6:(f"Flashback montage feel: Jay laughing and pointing at {YOU}'s old cracked phone at a party.",['Y','J']),
7:("Close-up of an old worn phone with a cracked corner, held in a hand, warm light.",['S']),
8:(f"Split composition: left a single old cracked phone, right a row of 14 small repair shop storefronts; {OLDER} standing in the middle.",['Y']),
9:(f"Restaurant table: three friends showing off brand-new phones, {YOU} at the end of the table.",['S','Y','J','T','M']),
10:("Close-up on the table: three shiny new phones in matching new cases and three pairs of wireless earbuds.",['S']),
11:(f"Friends line up their new phones on the dinner table like trophies, laughing; {YOU} watches.",['S','Y','J','T','M']),
12:(f"{YOU} looks at his old phone: a crack across the corner and a red low-battery icon, clock showing 3:00 PM.",['Y']),
13:(f"Jay throws an arm around {YOU}, holding up his new phone: 'treat yourself' energy.",['Y','J']),
14:(f"Night: {YOU} walks into a bright modern phone store with glowing display tables.",['Y']),
15:(f"Friendly salesman presents a gleaming new phone on a display stand to {YOU}; a big price tag hangs next to it.",['Y']),
16:(f"Salesman smiling, holding up a card that shows a small monthly payment; {YOU} raises an eyebrow.",['Y']),
17:(f"Night: {YOU} driving home in an old small car, thinking, city lights through the windshield.",['Y']),
18:(f"{YOU} parked in his car at night writing numbers on the back of a receipt with a pen.",['Y']),
19:("Simple infographic on a soft beige background: a phone icon, a shield icon and a phone-case icon, each with a small dollar amount, stacking up.",['S']),
20:("Simple infographic on beige: a phone plan card upgraded from basic to premium with an arrow pointing up.",['S']),
21:("Simple infographic on beige: a big stack of cash labeled per month and an even taller stack labeled per year.",['S']),
22:("Calendar pages flying; each year a new phone box appears in a growing stack beside them.",['S']),
23:(f"{YOU} looking at a long treadmill of new phone boxes moving past him, thoughtful.",['Y']),
24:(f"{YOU} holding his old cracked phone firmly, determined expression, at his small apartment desk at night.",['Y']),
25:(f"{YOU} on a laptop setting up an automatic bank transfer; coins flowing into a piggy bank shaped like a phone.",['Y']),
26:(f"Close-up of a laptop screen with a savings account nicknamed with a cracked-phone icon; {YOU} smirking.",['Y']),
27:("Close-up of the cracked phone screen; the crack spreading further across the glass.",['S']),
28:(f"{YOU} squinting at his phone, the crack now running through the middle of the screen.",['Y']),
29:(f"Mall repair kiosk: a technician quotes a price on a little sign; {YOU} looks shocked.",['Y']),
30:(f"{YOU} at home on his couch watching a repair tutorial video on a laptop, phone in hand.",['Y']),
31:(f"Small cardboard delivery box opened on a table: a replacement phone screen and a tiny screwdriver kit; {YOU} unpacking it.",['Y']),
32:(f"Kitchen table at night: {YOU} carefully opening a phone with a heat gun and tiny tools, sweating, focused, a delicate ribbon cable visible.",['Y']),
33:(f"The repaired phone lights up perfectly; {YOU} grins in triumph at the kitchen table.",['Y']),
34:("Simple comparison infographic on beige: a small receipt with a tiny cost versus a big receipt with a large cost, the big one crossed out.",['S']),
35:(f"{YOU} looking at the fixed phone, a soft glow suggesting an idea forming.",['Y']),
36:("Parking lot: Tasha drops her phone, it hits the asphalt, glass shattering, her hands up in panic.",['T']),
37:("Tasha showing her shattered phone, worried, standing in a hallway.",['T']),
38:(f"{YOU} confidently holding out his hand for Tasha's broken phone.",['Y','T']),
39:(f"Kitchen table: {YOU} replacing Tasha's phone screen; then Tasha happily holding her like-new phone.",['Y','T']),
40:("Tasha showing her fixed phone to a coworker in an office break room, both impressed.",['T']),
41:(f"Kitchen table covered with four broken phones in a neat row with little name notes; {YOU} with tools.",['Y']),
42:("Simple infographic on beige: a phone repair icon with a price tag and a smaller parts cost tag.",['S']),
43:(f"{YOU} adding cash into a jar on his kitchen counter, the jar filling up week by week.",['Y']),
44:(f"Split day/night: {YOU} working at a warehouse by day, fixing phones at night.",['Y']),
45:(f"Jay smirking and pointing at {YOU}, calling him the phone guy, other friends laughing.",['Y','J','M']),
46:(f"Kitchen table overflowing with broken phones, parts boxes stacked on chairs; {YOU} looks around at the mess.",['Y']),
47:(f"Organized workbench with labeled bins; {YOU} sorting phones by problem.",['Y']),
48:("Three-panel simple illustration: a cracked screen, a swollen battery, a charging port stuffed with pocket lint.",['S']),
49:(f"Shopping mall: {YOU} walking up to a tiny phone repair kiosk on a Saturday.",['Y']),
50:("A tiny mall repair booth; Mr. Okafor behind the counter, reading glasses on a chain.",['O']),
51:("Tiny repair booth: a single stool, a wall of little plastic drawers full of parts, Mr. Okafor sitting on the stool.",['O']),
52:(f"{YOU} talking across the booth counter to Mr. Okafor, a little nervous.",['Y','O']),
53:(f"Mr. Okafor handing {YOU} a phone with a swollen bulging battery, deadpan.",['Y','O']),
54:(f"{YOU} working fast on the phone at the booth counter while Mr. Okafor watches silently, arms crossed.",['Y','O']),
55:("Mr. Okafor sitting on his stool rubbing his knee, tired, honest expression.",['O']),
56:(f"{YOU} leaning on the counter asking a question, curious.",['Y','O']),
57:("Mr. Okafor turning a handwritten notebook around on the counter to show the numbers.",['O']),
58:("Simple infographic on beige: a tiny booth icon with incoming money arrows.",['S']),
59:("Simple infographic on beige: money splitting into rent, parts and profit piles; the profit pile highlighted green.",['S']),
60:("Simple infographic: a tiny repair booth next to a parking space outline, the booth smaller than the parking spot.",['S']),
61:(f"Mr. Okafor holding out a set of keys over the counter toward {YOU}.",['Y','O']),
62:(f"{YOU} looking at a banking app showing his savings, slightly short of what he needs.",['Y']),
63:(f"{YOU} half turned away from the booth, then pausing as he remembers the receipt math from his car.",['Y']),
64:(f"{YOU} sketching a payment plan on a napkin for Mr. Okafor at the booth counter.",['Y','O']),
65:(f"{YOU} and Mr. Okafor shaking hands over the counter.",['Y','O']),
66:(f"Mr. Okafor laughing warmly holding a coffee cup, {YOU} grinning.",['Y','O']),
67:(f"{YOU} walking out of a warehouse for the last time, hard hat under his arm, smiling.",['Y']),
68:(f"Mr. Okafor teaching {YOU} at the booth workbench, pointing at a phone's circuit board.",['Y','O']),
69:(f"Mr. Okafor showing {YOU} a water-damage indicator inside a phone with a magnifier; boxes of bulk parts behind them.",['Y','O']),
70:("Mr. Okafor raising one finger to make a point, wise expression, a stopwatch on the counter.",['O']),
71:(f"The booth counter with a big stopwatch icon on a sign; {YOU} handing a fixed phone to a happy customer.",['Y']),
72:("Mall corridor: a rival repair shop with a long slow line; staff sending a customer toward the small booth.",['S']),
73:("Simple infographic on beige: a rising bar chart of monthly profit growing tall.",['S']),
74:("Dinner: Jay proudly holding up yet another brand-new phone to the friends.",['J','T','M']),
75:(f"Jay leaning toward {YOU} at dinner with a teasing smile.",['Y','J']),
76:(f"{YOU} looking at his same old phone with a new screen, a small receipt showing a tiny total.",['Y']),
77:(f"{YOU} shrugging with a calm smile, holding up his old phone.",['Y']),
78:(f"{YOU} standing at the booth looking out at the busy mall crowd, thoughtful.",['Y']),
79:("Mall crowd: many people walking past, all holding phones, the phones softly highlighted.",['S']),
80:("Slow-motion comic moment: three people in the mall each dropping their phones at the same time.",['S']),
81:(f"{YOU} with a lightbulb-moment expression at the booth.",['Y']),
82:(f"{YOU} holding a cracked phone and pointing at it, playful 'oh no' expression.",['Y']),
83:("Simple infographic: three phones getting bigger and pricier left to right, with curved glass edges, price tags rising.",['S']),
84:(f"Split image: Jay buying new phones on the left; the same phones arriving cracked at {YOU}'s repair booth on the right.",['Y','J']),
85:(f"{YOU} cutting a ribbon at a second small repair booth in another mall.",['Y']),
86:("A small mall repair booth with a simple blank sign and a wrench icon, no readable text.",['S']),
87:("Simple infographic on beige: a booth icon with a coin stack that refills within a calendar year.",['S']),
88:(f"Wide view: {OLDER} in a small parts warehouse with shelves of labeled boxes and five booth photos on the wall.",['Y']),
89:(f"{OLDER} watching Danny repair a phone incredibly fast at a workbench, impressed.",['Y','D']),
90:(f"{OLDER} handing Danny an envelope and shaking his hand.",['Y','D']),
91:("Danny teaching a small group of new technicians at a workbench.",['D']),
92:(f"{OLDER} leaning back in a chair, relaxed, looking at a calm steady line on a laptop chart.",['Y']),
93:("Simple infographic: identical monthly bars, perfectly steady, same height every month.",['S']),
94:(f"Small office: an accountant woman with glasses and a bun reviewing papers; {OLDER} sitting across the desk.",['Y']),
95:(f"The accountant looking up from the papers, eyebrows raised, at {OLDER}.",['Y']),
96:(f"{OLDER} shaking his head, unsure.",['Y']),
97:("Simple infographic on beige: a yearly profit coin stack multiplied by three to four into a much taller tower.",['S']),
98:(f"{OLDER} stunned, looking at a calculator showing a big number.",['Y']),
99:("A heat gun and the old cracked phone on a table beside a small trophy-like stack of money.",['S']),
100:(f"Ominous mood: dark clouds over the mall as {OLDER} looks worried.",['Y']),
101:("A huge bright repair chain store with giant glowing signs and billboards arriving in the mall, no readable text.",['S']),
102:("Grand opening event: balloons, crowds, staff handing out free screen protectors.",['S']),
103:(f"The flashy big chain store directly across the hall from the small repair booth; {OLDER} staring across.",['Y']),
104:("Simple infographic: a red arrow dropping sharply on a revenue chart.",['S']),
105:(f"{OLDER} at a desk surrounded by imagined ideas: price-cut signs, billboards, giveaways, stressed.",['Y']),
106:(f"{OLDER} on the phone; inset: Mr. Okafor, retired, answering in his cozy living room.",['Y','O']),
107:("Mr. Okafor on the phone in his armchair, calm, asking a question.",['O']),
108:(f"{OLDER} on the phone, gesturing at the giant rival store across the hall.",['Y']),
109:("Mr. Okafor smiling knowingly on the phone.",['O']),
110:(f"{OLDER} sitting quietly thinking, phone to his ear, sunset light.",['Y']),
111:(f"{OLDER} looking through the window at Danny and techs working, a regular customer waving, a one-hour timer sign.",['Y','D']),
112:("Mr. Okafor on the phone, firm encouraging expression, pointing a finger.",['O']),
113:(f"{OLDER} calmly walking past price-cut signs and billboards without looking at them.",['Y']),
114:(f"{OLDER} with a notepad, walking toward a school, a delivery depot and a hospital.",['Y']),
115:("Three-panel: a school with students holding tablets, delivery drivers with cracked phones, a hospital with work devices.",['S']),
116:(f"{OLDER} shaking hands with a school administrator over a simple one-page contract.",['Y']),
117:("Danny's workbench stacked high with crates of broken school tablets.",['D']),
118:("Simple infographic: a pie chart with a third of it highlighted labeled with a briefcase icon.",['S']),
119:("The big chain store with a dark storm cloud and a falling chart behind it.",['S']),
120:("The big chain store closed: shutters down, a closed sign shape with no readable text, empty hallway.",['S']),
121:(f"Liquidation auction: {OLDER} raising a paddle as repair equipment is sold.",['Y']),
122:("Simple infographic on beige: a map with 14 pins, 41 people icons, school and hospital icons.",['S']),
123:("Simple infographic: a tall coin tower nearly reaching a line marked one million.",['S']),
124:(f"{OLDER} getting into a modest used hatchback outside a normal apartment building.",['Y']),
125:(f"Close-up of {OLDER}'s hand holding the same old phone.",['Y']),
126:("The old phone surrounded by small icons: four screens and three batteries, comic and slightly ridiculous.",['S']),
127:("Jay with a stack of eight phone boxes and two credit cards sweating in his wallet.",['J']),
128:(f"Jay's birthday dinner with a cake; Jay turns toward {OLDER}.",['Y','J','T','M']),
129:(f"Jay puzzled, asking {OLDER} a question across the table.",['Y','J']),
130:(f"{OLDER} about to speak, then pausing, a small smile.",['Y']),
131:("Comic contrast: a flashy man bragging with shopping bags next to a calm man quietly reading.",['S']),
132:(f"{OLDER} smiling and shrugging at the dinner table; Jay shaking his head.",['Y','J']),
133:(f"{OLDER} in a small office answering a phone call, a sleek corporate skyline outside.",['Y']),
134:("Map of a country with repair shop icons being gathered by a big corporate hand.",['S']),
135:("Simple infographic: a giant offer check with lots of zeros, no readable text.",['S']),
136:(f"{OLDER} on a call with Mr. Okafor, now 72, white beard, in his garden.",['Y','O']),
137:("Mr. Okafor in his garden on the phone asking a question.",['O']),
138:(f"{OLDER} shaking his head calmly on the phone.",['Y']),
139:("Mr. Okafor holding up a pie and cutting a small slice out of it, wise smile.",['O']),
140:(f"Signing table: {OLDER} signs papers with investors; Danny stands beside him.",['Y','D']),
141:(f"{OLDER} mailing an envelope at a mailbox, calm satisfied expression.",['Y']),
142:("Mr. Okafor sticking a sticky note on a check at his kitchen table, chuckling.",['O']),
143:("Close-up of a sticky note on a check with a little coffee cup doodle, no readable text.",['S']),
144:(f"Back at the repair shop counter: Jay holding up his shattered phone toward {OLDER}.",['Y','J']),
145:(f"{OLDER} in the back room of the shop replacing the screen at a workbench, focused.",['Y']),
146:("The repaired phone glowing, good as new, on the workbench.",['S']),
147:(f"{OLDER} handing the fixed phone back to a delighted Jay over the counter.",['Y','J']),
148:(f"Jay grinning and pointing at {OLDER}, joking; staff in the background smiling knowingly.",['Y','J']),
149:(f"Close-up: {OLDER} checking the time on his old phone with the cracked corner.",['Y']),
150:(f"{OLDER} standing outside the repair shop at sunset, reflective.",['Y']),
151:("Comic: friends' new phones turning into money flowing into a repair shop.",['S']),
152:(f"{OLDER} quietly walking past a busy shopping street, people with phones everywhere.",['Y']),
153:(f"{OLDER} at a workbench fixing an old phone, a line of people with broken phones waiting happily.",['Y']),
154:(f"{OLDER} giving a small friendly wave, sitting on a bench outside the repair shop at dusk.",['Y']),
155:(f"{OLDER} holding up his old phone toward the viewer with a curious smile.",['Y']),
}
