# scene_id: (prompt, [ref keys]); refs: A=adult you, Y=young you, D=Dolores, T=Tyson, R=Rosa, W=Sunny Wash interior, I=infographic style, S=style only
A='7ba7033e-2000-4edb-b231-5414dd35a15a'; I='d798f243-2f66-4d99-8c5a-515b01db6d2f'; S='5d7f64b3-ccb2-4068-bf24-02095a40602e'
SC={
'c1':("Dawn inside a clean laundromat; the calm mid-40s man (short dark hair greying at temples, old grey sweatshirt) kneels behind a row of dryers with a small flashlight held in his teeth, cleaning a dryer vent. Soft blue early light through front windows.",['A']),
'c2':("Close-up of a dryer lint vent packed with thick grey felt lint, a hand in a work glove pulling it out in one big sheet.",['S']),
'c3':("Close-up of a worn grey sweatshirt cuff with a small hole, the man's hand holding a flashlight; blurred laundromat front door opening with a little bell in the background.",['A']),
'c4':("A 19-year-old college student with messy hair, hoodie and backpack drags a black garbage bag full of clothes through the front door of a clean laundromat at dawn.",['S']),
'c5':("The same college student frowning and pointing at a coin change machine on the laundromat wall.",['c4']),
'c6':("The calm mid-40s man in the old grey sweatshirt opens the change machine with a key from a big key ring and hands five one-dollar bills to the college student.",['A','c4']),
'c7':("The college student walks away carrying his laundry, not looking back; the calm man in the grey sweatshirt watches with a tiny private smile.",['A','c4']),
'c8':("Morning in a flashy modern apartment: Tyson asleep in a big bed, phone on the nightstand, designer clothes on a chair, bedside clock reading 9:40.",['T']),
'c9':("Tyson in the driver's seat of the shiny black luxury sedan taking a selfie; on the passenger seat a lease contract with '$940/MO' visible.",['T']),
'c10':("Close-up of a phone screen showing a social media post: Tyson at a rooftop bar at night with city lights, caption 'Built different'.",['T']),
'c11':("Family dinner at a restaurant table: Tyson in his flashy jacket confidently slides the check toward himself and waves it, the calm man in the plain grey sweatshirt sitting across, smiling politely.",['T','A']),
'c12':("Top-down map of a region with 38 small orange pins clustered in four cities, a label card reading '38 LAUNDROMATS'. Coffee mug on the desk.",['I']),
'c13':("Simple infographic on a soft beige background: a row of small building icons with '19 BUILDINGS OWNED' and a bar labeled '$11M REVENUE'.",['I']),
'c14':("Simple split infographic on beige: left 'YOU: ~$23M' with a small stack of laundromat icons; right 'TYSON: -$31K' with a credit card icon.",['I']),
'c15':("Late night at a bar booth: Tyson, a little tipsy, quietly confides something to the calm man in the grey sweatshirt, who listens.",['T','A']),
'c16':("Big family dinner table, everyone laughing and talking; Tyson in his flashy jacket in the middle of attention; the calm man in the plain grey sweatshirt sits quietly at the end of the table.",['T','A']),
'c17':("Flashback, slightly faded colors: the young 24-year-old man with short dark hair stands in a laundromat holding out his open palm with only a few coins in it.",['Y']),
'L1':("Chapter title card: solid deep navy background, a small orange washing machine icon, large clean white text 'LEVEL ONE' and below it smaller text 'The jar of quarters'.",['I']),
'L2':("Chapter title card: solid deep navy background, a small orange key icon, large clean white text 'LEVEL TWO' and below it smaller text 'The laundromat nobody wanted'.",['I']),
'L3':("Chapter title card: solid deep navy background, a small orange calendar icon, large clean white text 'LEVEL THREE' and below it smaller text 'The quiet years'.",['I']),
'L4':("Chapter title card: solid deep navy background, a small orange storm cloud icon, large clean white text 'LEVEL FOUR' and below it smaller text 'The bad year'.",['I']),
'L5':("Chapter title card: solid deep navy background, a small orange building icon, large clean white text 'LEVEL FIVE' and below it smaller text 'The quiet roll-up'.",['I']),
'L6':("Chapter title card: solid deep navy background, a small orange phone icon, large clean white text 'LEVEL SIX' and below it smaller text 'The phone call you didn't take'.",['I']),
's19':("The young man in his navy work uniform kneels in an apartment building basement laundry room repairing a commercial washer, tools spread on the floor.",['Y']),
's20':("Interior of the white service van: shelves of washer belts, parts boxes and detergent jugs; the young man in uniform grabbing a belt.",['Y']),
's21':("Night city sidewalk: the young man carrying a heavy duffel bag on his shoulder walks toward a small laundromat with a glowing sign 'SUNNY WASH'.",['Y']),
's22':("Inside a tired old laundromat at night: several dryers with handwritten 'OUT OF ORDER' paper signs, buzzing fluorescent tube lights, a crack in the floor shaped like a lightning bolt. No people.",['S']),
's24':("Dryer number 6 (big '6' on the door) stopped mid-cycle with wet clothes inside; the young man in a casual hoodie looks at it.",['Y','W']),
's25':("The young man has the back panel off the dryer, a small screwdriver on his keychain, holding up a snapped rubber belt.",['Y','W']),
's26':("Dolores puts down her crossword and looks at the young man across the counter with interest; he stands holding the broken belt.",['D','Y']),
's27':("Dolores pours coffee from a thermos into a cup for the young man and turns an old ledger book around on the counter toward him.",['D','Y']),
's28':("Close-up of an old ledger page filled with handwritten numbers in blue pen, a pair of reading glasses on a beaded chain resting on it.",['D']),
's29':("Simple infographic on beige: a washing machine icon with two labels 'COST PER LOAD: 40¢' and 'PRICE: $3.25'.",['I']),
's30':("Customers in a laundromat inserting quarters and tapping cards into machines before starting them, calm everyday scene.",['W']),
's31':("Simple infographic on beige: a small worn laundromat icon with a label '~$8,000 / MONTH PROFIT'.",['I']),
's32':("Dolores looks softly at an old framed photo of a smiling older man on the wall behind the counter, her crossword set aside.",['D']),
's34':("The young man at a small kitchen table at night looking at his phone banking app showing a new savings account named 'Machines' and an automatic transfer of '$200'.",['Y']),
's35':("A glass jar on a shelf slowly filling with coins as calendar pages fly away in the background, simple and quiet.",['S']),
's37':("Split screen phone call: left the young man in his work uniform on his phone in the van; right Dolores on an old phone at her counter.",['Y','D']),
's38':("A sleek businessman in a suit holds a blueprint labeled 'PHONE STORE' outside the tired Sunny Wash laundromat, looking at the corner.",['S']),
's39':("Simple infographic on beige: 'OFFER: $310,000' next to 'PROFIT: $96K / YEAR' with a laundromat icon.",['I']),
's40':("Simple infographic on beige: a laundromat icon with a bracket showing '3–4x YEARLY PROFIT = FAIR PRICE'.",['I']),
's41':("The young man frowning at his phone showing a savings balance '$44,000' labeled 'Machines'.",['Y']),
's42':("Flashback: the young man in uniform and his older boss (grey mustache, cap) fixing a machine in a retirement community laundry room, the boss talking.",['Y']),
's43':("Late night: the young man at a desk with library books about small business loans, a laptop and sticky notes.",['Y']),
's44':("Small community bank office: the young man in a brand-new tie sits across from a friendly loan officer named Gary (bald, glasses, sweater vest).",['Y']),
's45':("Simple infographic on beige: a stacked bar of three blocks '$31K YOUR DOWN PAYMENT', '$232K BANK LOAN (10 YEARS)', '$47K SELLER NOTE', next to a laundromat icon '$310K'.",['I']),
's48':("Dolores with arms crossed and skeptical eyebrows across the counter from the young man, who is earnestly explaining.",['D','Y']),
's49':("Rosa folding laundry at the old Sunny Wash, smiling at a regular customer.",['R','W']),
's50':("Dolores signs the sale papers at her counter with a pen while the young man watches; coffee cups nearby.",['D','Y']),
's52':("Dolores places a heavy ring of keys into the young man's hand at the laundromat counter, warm smile.",['D','Y']),
's54':("A broken water heater leaking water in a laundromat back room; the young man with a plumber looking at it, worried.",['Y']),
's56':("Night: the young man alone at the laundromat counter writing numbers into a small notebook, machines quiet behind him.",['Y','W']),
's57':("Simple infographic on beige: monthly bills as bars 'WATER $2,100', 'GAS $1,800', 'POWER $1,300', plus 'STAFF', 'LOAN', 'REPAIRS'.",['I']),
's58':("Simple infographic on beige: 'REVENUE $22,400' arrow down to 'YOU KEEP $6,200' with a green check.",['I']),
's59':("The young man asleep in bed at night while his phone on the nightstand lights up with a deposit notification.",['Y']),
's61':("Split scene: left the young man in his uniform leaving the route company van at sunset; right the same man at night working inside Sunny Wash.",['Y']),
's62':("The young man on a ladder installing bright LED lights in the laundromat; the floor crack freshly patched; machines all working.",['Y','W']),
's63':("Close-up of a card reader on a washer, a customer tapping a card; small screen shows 'PAID'.",['S']),
's64':("Wash-and-fold counter with labeled laundry bags; Rosa weighing a bag on a scale and folding.",['R']),
's65':("Rosa smiling as the young man hands her an envelope; a small sign on the wall 'WASH & FOLD — PER POUND'.",['R','Y']),
's66':("Simple bar chart on beige: 'YEAR 1: $96K' short bar and 'YEAR 3: $161K' tall bar.",['I']),
's67':("Exterior of the renovated Sunny Wash at daytime: bright, clean, fresh paint, customers inside, same small corner building.",['S']),
's68':("Family backyard barbecue: Tyson pulls up in a shiny new luxury car, waving out the window to the young man holding a paper plate.",['T','Y']),
's69':("Inside the luxury car: Tyson taps a big dashboard screen proudly; the young man in the passenger seat nods politely.",['T','Y']),
's71':("Simple infographic on beige: '$680/MO LEASE' with an arrow to 'A USED COMMERCIAL WASHER EVERY 2 MONTHS'.",['I']),
's72':("Simple infographic on beige: a washer icon with 'PAYS FOR ITSELF IN ~2 YEARS' and 'EARNS FOR 15 YEARS'.",['I']),
's73':("Split infographic: left a car with a red arrow going down 'LOSES VALUE'; right a washer with coins coming out 'PAYS EVERY LOAD'.",['I']),
's74':("The young man quietly looking out the car window while Tyson keeps talking and gesturing.",['T','Y']),
's75':("The young man shakes hands with his older boss (grey mustache, cap) next to the white service van; boss smiling.",['Y']),
's77':("The young man at home writing a Christmas card at a table, a small decorated tree behind.",['Y']),
's78':("A postcard on a wooden table showing a sunny beach on the front, next to a stack of paid loan statements stamped 'PAID'.",['S']),
's79':("Close-up of the back of a postcard with neat handwriting: 'Told you machines pay.'",['S']),
's81':("A brand-new flashy laundromat with a huge glass front and a bright sign 'SPINCITY', balloons, three blocks down the street from a small modest laundromat.",['S']),
's82':("SpinCity grand opening: a DJ booth, crowds, a banner 'FREE DETERGENT FOR A MONTH', a big phone app sign.",['S']),
's83':("Simple line chart on beige: revenue line dropping sharply with a red label '-28%'.",['I']),
's84':("The man, now about 31, sitting at the laundromat counter at night, stressed, looking at bills marked 'LOAN', 'DOLORES NOTE', 'PAYROLL'.",['Y']),
's85':("Split phone call: left the 31-year-old man worried on the phone; right Dolores, now about 75, calm, crossword in hand, on her phone.",['Y','D']),
's86':("The man driving a small white van around town, a list of local businesses on the passenger seat, knocking on a door.",['Y']),
's87':("A gym laundry area overflowing with towel bins; next to it a vacation rental bedroom with sheets being stripped.",['S']),
's88':("A small nursing home laundry room with a broken washer and an out-of-order sign; a barbershop and a yoga studio storefront next door.",['S']),
's89':("Close-up of simple service contracts being signed on a clipboard, with a monthly invoice beside it.",['S']),
's90':("Early morning: a white delivery van labeled 'WASH & FOLD DELIVERY' unloading neat laundry bags at a nursing home entrance.",['S']),
's91':("Simple pie chart on beige: '34% COMMERCIAL ACCOUNTS' slice highlighted in orange, rest 'WALK-IN'.",['I']),
's92':("The flashy SpinCity laundromat dark and closed, a 'CLOSED' sign on the glass door, balloons deflated.",['s81']),
's93':("Warehouse auction: rows of washers with lot tags; the man raises a bidding paddle; a sign '19¢ ON THE DOLLAR'.",['Y']),
's94':("Close-up of a notebook page with handwritten line: 'Don't fight the loud competitor. Serve the customers they ignore.'",['S']),
's97':("Simple infographic on beige: two laundromat icons and a delivery van icon with '≈ $400K / YEAR'.",['I']),
's98':("A tired elderly laundromat owner (white hair, glasses) sitting alone behind the counter of an old 1980s laundromat, old photos on the wall.",['S']),
's100':("The calm mid-40s man (short dark hair greying, plain grey sweatshirt) shaking hands warmly with an elderly laundromat owner in front of their small store.",['A']),
's101':("A plain incorporation document on a desk titled 'NORTHGATE LAUNDRY GROUP' with a pen and a coffee cup.",['S']),
's102':("A street montage of four small different laundromat storefronts with their own local signs: 'SUNNY WASH', 'BUBBLES ON FIFTH', 'THE SPIN CYCLE', 'CORNER COIN WASH'.",['S']),
's104':("The calm mid-40s man at a simple desk, thinking, with a notebook and a calculator.",['A']),
's105':("Simple infographic on beige: one small laundromat icon '1 STORE: 3–4x PROFIT'.",['I']),
's106':("Simple infographic on beige: a group of twenty laundromat icons with a manager badge '20 STORES: 6–7x PROFIT'.",['I']),
's107':("Close-up still life: a washer door, a few quarters and a puff of dryer lint on a folding table.",['S']),
's108':("Simple infographic on beige: a laundromat bought at '3.5x' moving into a group box labeled 'NORTHGATE', arrow up '~2x VALUE'.",['I']),
's110':("A small laundromat with the whole building outlined in orange, a label 'OWN THE BUILDING'.",['I']),
's111':("A smug landlord in a suit holding a lease with a big red arrow pointing up, standing outside a laundromat.",['S']),
's112':("Simple diagram on beige: 'LAUNDROMAT CO.' paying rent with an arrow to 'PROPERTY CO.', both inside a circle labeled 'YOURS'.",['I']),
's113':("Simple chart on beige: a 'BUILDING VALUE' line rising while a 'LOAN BALANCE' line falls.",['I']),
's115':("A busy laundromat near a college campus with students coming and going; label on window 'STORE 9'.",['S']),
's117':("A landlord across the street watching a long line of students out the door of the laundromat on a Sunday, rubbing his chin.",['s115']),
's118':("The calm mid-40s man reading a letter 'RENT INCREASE: 3x' at a desk covered in spreadsheets, frowning.",['A']),
's119':("Workers moving washers on dollies down a sidewalk to a smaller storefront two blocks away; a floating label '-$140,000'.",['S']),
's120':("Close-up notebook page with handwriting underlined twice: 'If you don't own the dirt, you don't own the business.'",['S']),
's122':("The calm man handing a thick binder labeled 'PLAYBOOK' to a new store manager inside a bright laundromat.",['A']),
's123':("Rosa, now operations director, in a small office with a tablet and a wall map of many stores, confident.",['R']),
's124':("Tyson in his apartment surrounded by stacks of sneaker boxes, pitching enthusiastically with his phone in hand.",['T']),
's125':("The calm man in the grey sweatshirt smiling politely and shaking his head slightly at Tyson.",['A','T']),
's126':("Dawn in an apartment parking lot: a tow truck hauling away Tyson's shiny black sedan; a 'REPOSSESSED' notice.",['T']),
's127':("Tyson sitting on his apartment steps, embarrassed, on the phone.",['T']),
's128':("The calm man on the phone at his desk, listening kindly.",['A']),
's129':("Tyson in a work polo shirt standing proudly next to a white laundry delivery van.",['T']),
's131':("Tyson charming a gym owner at the front desk, the owner laughing and signing a laundry contract.",['T']),
's132':("Tyson high-fiving Rosa in the operations office in front of a board with 19 new account cards.",['T','R']),
's133':("Tyson leaning on another new shiny black leased sedan, grinning, keys in hand.",['T']),
's136':("The calm mid-40s man at his office window taking a phone call, city in the background.",['A']),
's137':("An offer letter on a desk with the line 'PURCHASE OFFER: $15,000,000' highlighted.",['S']),
's138':("Dolores at 84 at her daughter's kitchen table, doing a crossword in pencil, on the phone, smiling.",['D']),
's140':("Dolores laughing warmly on the phone, waving her pencil.",['D']),
's141':("Simple pie chart on beige: 'SOLD MINORITY STAKE: $4.2M' small slice, 'YOU KEEP CONTROL' big slice, and a row of building icons 'ALL BUILDINGS KEPT'.",['I']),
's142':("Simple infographic on beige: six new laundromat icons appearing with plus signs.",['I']),
's143':("Simple diagram on beige: laundromat icons labeled 'MAKE THE MONEY' feeding into building icons labeled 'HOLD THE MONEY', value arrow rising.",['I']),
's145':("The calm mid-40s man driving an old dented pickup truck down a quiet street, relaxed.",['A']),
's146':("Spring funeral outside a small church: Dolores's middle-aged daughter hands the calm man in a dark suit an envelope.",['A']),
's147':("Close-up of a torn old ledger page in blue pen held in a man's hands.",['s28']),
's148':("Extreme close-up of the ledger page margin with shaky handwriting: 'He fixed dryer six for free. Sell it to him.'",['s28']),
's150':("Well-paid smiling staff in matching shirts cleaning dryer vents and wiping machines in a bright laundromat.",['S']),
's153':("Restaurant dinner: Tyson grabs the check with a grin; the calm man in the grey sweatshirt lets him, smiling.",['T','A']),
's154':("Rules card on a deep navy background with three clean white lines: '1. Buy the boring business.' '2. Serve the customers they ignore.' '3. Own the building.'",['I']),
's158':("A small neighborhood laundromat glowing warmly at night on a quiet corner, machines turning inside, nobody around.",['S']),
}
# segment -> scene
MAP={1:'c1',2:'c2',3:'c3',4:'c4',5:'c5',6:'c6',7:'c7',8:'c8',9:'c9',10:'c10',11:'c11',12:'c12',13:'c13',14:'c14',15:'c15',16:'c16',17:'c17',
18:'L1',19:'s19',20:'s20',21:'s21',22:'s22',23:'D0',24:'s24',25:'s25',26:'s26',27:'s27',28:'s28',29:'s29',30:'s30',31:'s31',32:'s32',33:'s32',34:'s34',35:'s35',
36:'L2',37:'s37',38:'s38',39:'s39',40:'s40',41:'s41',42:'s42',43:'s43',44:'s44',45:'s45',46:'s45',47:'s45',48:'s48',49:'s49',50:'s50',51:'s50',52:'s52',53:'s52',54:'s54',55:'s54',56:'s56',57:'s57',58:'s58',59:'s59',
60:'L3',61:'s61',62:'s62',63:'s63',64:'s64',65:'s65',66:'s66',67:'s67',68:'s68',69:'s69',70:'s69',71:'s71',72:'s72',73:'s73',74:'s74',75:'s75',76:'s75',77:'s77',78:'s78',79:'s79',
80:'L4',81:'s81',82:'s82',83:'s83',84:'s84',85:'s85',86:'s86',87:'s87',88:'s88',89:'s89',90:'s90',91:'s91',92:'s92',93:'s93',94:'s94',95:'s94',
96:'L5',97:'s97',98:'s98',99:'s98',100:'s100',101:'s101',102:'s102',103:'s102',104:'s104',105:'s105',106:'s106',107:'s107',108:'s108',109:'s108',110:'s110',111:'s111',112:'s112',113:'s113',114:'s113',115:'s115',116:'s115',117:'s117',118:'s118',119:'s119',120:'s120',121:'s120',122:'s122',123:'s123',124:'s124',125:'s125',126:'s126',127:'s127',128:'s128',129:'s129',130:'s129',131:'s131',132:'s132',133:'s133',134:'s133',
135:'L6',136:'s136',137:'s137',138:'s138',139:'s138',140:'s140',141:'s141',142:'s142',143:'s143',144:'s143',145:'s145',146:'s146',147:'s147',148:'s148',
149:'c1',150:'s150',151:'c2',152:'c11',153:'s153',154:'s154',155:'s154',156:'c6',157:'c7',158:'s158',159:'s158',160:'s158'}
